// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type APIKey struct {
	APIKey    string     `json:"api_key"`
	Expired   bool       `json:"expired"`
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	LastUsed  *time.Time `json:"last_used,omitempty"`
	Name      string     `json:"name"`
}
