// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type APIKeysCreateParams struct {
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	Name      string     `json:"name"`
}
