// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionSpec struct {
	Auth    ConnectionAuth        `json:"auth"`
	Icon    string                `json:"icon"`
	ID      string                `json:"id"`
	Name    string                `json:"name"`
	Request ConnectionRequestSpec `json:"request"`
}
