// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionParamsGithubVariant struct {
	Name  *string                `json:"name,omitempty"`
	Type  ConnectionType         `json:"type"`
	Value ConnectionParamsGithub `json:"value"`
}
