// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ConnectionAuthType string

const (
	ConnectionAuthTypeOauth2 ConnectionAuthType = "Oauth2"
)

func (e ConnectionAuthType) ToPointer() *ConnectionAuthType {
	return &e
}

func (e *ConnectionAuthType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Oauth2":
		*e = ConnectionAuthType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionAuthType: %v", v)
	}
}
