// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionSpecListing struct {
	Items []ConnectionSpec `json:"items"`
	Next  *string          `json:"next,omitempty"`
	Prev  *string          `json:"prev,omitempty"`
}
