// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionListing struct {
	Items []Connection `json:"items"`
	Next  *string      `json:"next,omitempty"`
	Prev  *string      `json:"prev,omitempty"`
}
