// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Demo struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	ID        *int64     `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UserID    *string    `json:"user_id,omitempty"`
}
