// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type DirectorySyncAdminPortal struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Link      *string    `json:"link,omitempty"`
}
