// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type DirectorySync struct {
	CreatedAt   time.Time `json:"created_at"`
	DirectoryID string    `json:"directory_id"`
	Domains     []string  `json:"domains,omitempty"`
	ID          string    `json:"id"`
	Name        *string   `json:"name,omitempty"`
	Type        *string   `json:"type,omitempty"`
	UpdatedAt   time.Time `json:"updated_at"`
}
