// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Error struct {
	Code    string  `json:"code"`
	DocURL  *string `json:"doc_url,omitempty"`
	Message string  `json:"message"`
	Param   *string `json:"param,omitempty"`
	Type    string  `json:"type"`
}
