// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type GenerateGithubVariantType string

const (
	GenerateGithubVariantTypeGithub GenerateGithubVariantType = "Github"
)

func (e GenerateGithubVariantType) ToPointer() *GenerateGithubVariantType {
	return &e
}

func (e *GenerateGithubVariantType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Github":
		*e = GenerateGithubVariantType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GenerateGithubVariantType: %v", v)
	}
}

type GenerateGithubVariant struct {
	Type  GenerateGithubVariantType `json:"type"`
	Value GenerateGithub            `json:"value"`
}
