// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GenerateGithub struct {
	Append string `json:"append"`
	Path   string `json:"path"`
	Repo   string `json:"repo"`
}
