// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GithubEnterpriseAppParams struct {
	ClientID *string `json:"client_id,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	ID       *string `json:"id,omitempty"`
	Org      *string `json:"org,omitempty"`
	Pem      *string `json:"pem,omitempty"`
}
