// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GithubEnterpriseApp struct {
	Hostname *string `json:"hostname,omitempty"`
	ID       *string `json:"id,omitempty"`
	Org      *string `json:"org,omitempty"`
}
