// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Grant - Success
type Grant struct {
	CreatedAt         time.Time `json:"created_at"`
	Deleted           bool      `json:"deleted"`
	GrantKitID        string    `json:"grant_kit_id"`
	GrantKitVersionID string    `json:"grant_kit_version_id"`
	ID                string    `json:"id"`
	OrganizationID    string    `json:"organization_id"`
	RequestID         string    `json:"request_id"`
	UpdatedAt         time.Time `json:"updated_at"`
	UserID            string    `json:"user_id"`
}
