// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GrantKitPolicySet struct {
	GrantIf  []Policy `json:"grant_if,omitempty"`
	RevokeIf []Policy `json:"revoke_if,omitempty"`
}
