// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type GrantKitVersion struct {
	CreatedAt    time.Time      `json:"created_at"`
	Description  string         `json:"description"`
	GrantKitID   string         `json:"grant_kit_id"`
	GrantKitName string         `json:"grant_kit_name"`
	ID           string         `json:"id"`
	Output       Output         `json:"output"`
	Policies     []Policy       `json:"policies"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Version      int64          `json:"version"`
	Workflow     *GrantWorkflow `json:"workflow"`
}
