// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Identity - Created
type Identity struct {
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	// See documentation
	Linked interface{} `json:"linked,omitempty"`
	Name   string      `json:"name"`
}
