// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IdentityParams struct {
	AbbeyAccount string `json:"abbey_account"`
	// Json encoded string. See documentation for details.
	Metadata string `json:"metadata"`
	Source   string `json:"source"`
}
