// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Identity - Created
type Identity struct {
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	// Json encoded string. See documentation for details
	Linked *string `json:"linked,omitempty"`
	Name   string  `json:"name"`
}
