// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IdentityParams struct {
	Linked map[string][]interface{} `json:"linked"`
	Name   string                   `json:"name"`
}
