// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IdentityParams struct {
	// Json encoded string. See documentation for details
	Linked string `json:"linked"`
	Name   string `json:"name"`
}
