// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type KeyValuePair struct {
	Key string `json:"key"`
	// A meta-schema conforming to the official JSON Schema core/validation dialect 2020-12 meta-schema.
	//
	Value interface{} `json:"value,omitempty"`
}
