// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Oauth struct {
	Application *string `json:"application,omitempty"`
	CreatedDate *string `json:"created_date,omitempty"`
}
