// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OAuthCreateParams struct {
	Application *string `json:"application,omitempty"`
	Code        *string `json:"code,omitempty"`
}
