// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OauthListing struct {
	Items []Oauth `json:"items"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
}
