// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrganizationGrantKitCount struct {
	GrantKitCount    int64  `json:"grant_kit_count"`
	OrganizationName string `json:"organization_name"`
}
