// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Output struct {
	Append    *string `json:"append,omitempty"`
	Location  string  `json:"location"`
	Overwrite *string `json:"overwrite,omitempty"`
}
