// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PagerdutyConnectionValue struct {
	Name  *string             `json:"name,omitempty"`
	Type  ConnectionType      `json:"type"`
	Value PagerdutyConnection `json:"value"`
}
