// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PagerdutyConnection struct {
	ClientInfo   string  `json:"client_info"`
	IDToken      string  `json:"id_token"`
	RefreshToken string  `json:"refresh_token"`
	Scope        string  `json:"scope"`
	TokenType    *string `json:"token_type,omitempty"`
}
