// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestableParams struct {
	Description string             `json:"description"`
	Grant       Grant              `json:"grant"`
	Name        string             `json:"name"`
	Policies    *GrantKitPolicySet `json:"policies,omitempty"`
	Workflow    *Workflow          `json:"workflow,omitempty"`
}
