// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestParams struct {
	GrantKitID string     `json:"grant_kit_id"`
	Reason     string     `json:"reason"`
	UserInput  *UserInput `json:"user_input,omitempty"`
}
