// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestRevokeParams struct {
	// The reason for revoking the request
	Reason *string `json:"reason,omitempty"`
}
