// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestCancelParams struct {
	// The reason for canceling the request
	Reason *string `json:"reason,omitempty"`
}
