// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestParams struct {
	Reason       *string                          `json:"reason,omitempty"`
	Requestables []RequestParamsRequestablesInner `json:"requestables"`
}
