// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestParamsRequestablesInner struct {
	ID    string      `json:"id"`
	Input interface{} `json:"input"`
}
