// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RequestSpec struct {
	// A value conforming to the official JSON Schema core/validation dialect 2020-12 meta-schema.
	//
	Body        interface{}         `json:"body,omitempty"`
	ContentType *RequestContentType `json:"content_type,omitempty"`
	Method      HTTPMethod          `json:"method"`
	URL         string              `json:"url"`
}
