// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ResourceRequestCount struct {
	RequestCount int64  `json:"request_count"`
	ResourceName string `json:"resource_name"`
}
