// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Review struct {
	Decision     string  `json:"decision"`
	Reason       *string `json:"reason,omitempty"`
	ReviewerName string  `json:"reviewer_name"`
}
