// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Review - Success
type Review struct {
	CreatedAt         time.Time    `json:"created_at"`
	GrantID           string       `json:"grant_id"`
	GrantKitVersionID string       `json:"grant_kit_version_id"`
	ID                string       `json:"id"`
	Reason            string       `json:"reason"`
	RequestID         string       `json:"request_id"`
	Status            ReviewStatus `json:"status"`
	UpdatedAt         time.Time    `json:"updated_at"`
	UserID            string       `json:"user_id"`
}
