// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SamlConnection struct {
	AcsURL     string `json:"acs_url"`
	Active     bool   `json:"active"`
	ID         string `json:"id"`
	Name       string `json:"name"`
	Provider   string `json:"provider"`
	SpEntityID string `json:"sp_entity_id"`
}
