// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SamlConnectionParams struct {
	Domain         string  `json:"domain"`
	IdpCertificate *string `json:"idp_certificate,omitempty"`
	IdpEntityID    *string `json:"idp_entity_id,omitempty"`
	IdpSsoURL      *string `json:"idp_sso_url,omitempty"`
	Name           string  `json:"name"`
}
