// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SamlConnectionParams struct {
	Domain         string `json:"domain"`
	IdpCertificate string `json:"idp_certificate"`
	IdpEntityID    string `json:"idp_entity_id"`
	IdpSsoURL      string `json:"idp_sso_url"`
	Name           string `json:"name"`
}
