// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SlackCommand struct {
	APIAppID       *string `json:"api_app_id,omitempty"`
	ChannelID      *string `json:"channel_id,omitempty"`
	ChannelName    *string `json:"channel_name,omitempty"`
	Command        *string `json:"command,omitempty"`
	EnterpriseID   *string `json:"enterprise_id,omitempty"`
	EnterpriseName *string `json:"enterprise_name,omitempty"`
	ResponseURL    *string `json:"response_url,omitempty"`
	TeamDomain     *string `json:"team_domain,omitempty"`
	TeamID         *string `json:"team_id,omitempty"`
	Text           *string `json:"text,omitempty"`
	Token          *string `json:"token,omitempty"`
	TriggerID      *string `json:"trigger_id,omitempty"`
	UserName       *string `json:"user_name,omitempty"`
}
