// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Step struct {
	Reviewers *Reviewers `json:"reviewers,omitempty"`
	SkipIf    []Policy   `json:"skip_if,omitempty"`
}
