// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskParams struct {
	AssignTo          string  `json:"assign_to"`
	RequestID         string  `json:"request_id"`
	RequestedResource string  `json:"requested_resource"`
	WorkflowID        *string `json:"workflow_id,omitempty"`
}
