// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type UserInput struct {
	ExpireAt *time.Time `json:"expire_at,omitempty"`
	ExpireIn *string    `json:"expire_in,omitempty"`
}
