// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UserApprovalAnalytics struct {
	Approvals []UserApprovalCount `json:"approvals"`
	Denials   []UserApprovalCount `json:"denials"`
}
