// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UserApprovalCount struct {
	PrimaryEmailAddress string `json:"primary_email_address"`
	RequestCount        int64  `json:"request_count"`
}
