// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WorkOSDirectoryDataDomains struct {
	Domain *string `json:"domain,omitempty"`
	ID     *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
}

type WorkOSDirectoryData struct {
	CreatedAt      *time.Time                   `json:"created_at,omitempty"`
	Domains        []WorkOSDirectoryDataDomains `json:"domains,omitempty"`
	ExternalKey    *string                      `json:"external_key,omitempty"`
	ID             *string                      `json:"id,omitempty"`
	Name           *string                      `json:"name,omitempty"`
	Object         *string                      `json:"object,omitempty"`
	OrganizationID *string                      `json:"organization_id,omitempty"`
	State          *string                      `json:"state,omitempty"`
	Type           *string                      `json:"type,omitempty"`
	UpdatedAt      *time.Time                   `json:"updated_at,omitempty"`
}
