// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WorkOSGroupEvent struct {
	CreatedAt *time.Time       `json:"created_at,omitempty"`
	Data      *WorkOSGroupData `json:"data,omitempty"`
	Event     *string          `json:"event,omitempty"`
	ID        *string          `json:"id,omitempty"`
}
