// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WorkOSUserDataCustomAttributes struct {
}

type WorkOSUserDataEmails struct {
	Primary *bool   `json:"primary,omitempty"`
	Type    *string `json:"type,omitempty"`
	Value   *string `json:"value,omitempty"`
}

type WorkOSUserDataPreviousAttributes struct {
}

type WorkOSUserDataRawAttributes struct {
}

type WorkOSUserData struct {
	CreatedAt          *time.Time                        `json:"created_at,omitempty"`
	CustomAttributes   *WorkOSUserDataCustomAttributes   `json:"custom_attributes,omitempty"`
	DirectoryID        *string                           `json:"directory_id,omitempty"`
	Emails             []WorkOSUserDataEmails            `json:"emails,omitempty"`
	FirstName          *string                           `json:"first_name,omitempty"`
	ID                 *string                           `json:"id,omitempty"`
	IdpID              *string                           `json:"idp_id,omitempty"`
	JobTitle           *string                           `json:"job_title,omitempty"`
	LastName           *string                           `json:"last_name,omitempty"`
	Object             *string                           `json:"object,omitempty"`
	OrganizationID     *string                           `json:"organization_id,omitempty"`
	PreviousAttributes *WorkOSUserDataPreviousAttributes `json:"previous_attributes,omitempty"`
	RawAttributes      *WorkOSUserDataRawAttributes      `json:"raw_attributes,omitempty"`
	State              *string                           `json:"state,omitempty"`
	UpdatedAt          *time.Time                        `json:"updated_at,omitempty"`
	Username           *string                           `json:"username,omitempty"`
}
