// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WorkOSDirectoryEvent struct {
	CreatedAt *time.Time           `json:"created_at,omitempty"`
	Data      *WorkOSDirectoryData `json:"data,omitempty"`
	Event     *string              `json:"event,omitempty"`
	ID        *string              `json:"id,omitempty"`
}
