// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WorkOSGroupPreviousAttributes struct {
}

type WorkOSGroupRawAttributes struct {
}

type WorkOSGroup struct {
	CreatedAt          *time.Time                     `json:"created_at,omitempty"`
	DirectoryID        *string                        `json:"directory_id,omitempty"`
	ID                 *string                        `json:"id,omitempty"`
	IdpID              *string                        `json:"idp_id,omitempty"`
	Name               *string                        `json:"name,omitempty"`
	Object             *string                        `json:"object,omitempty"`
	OrganizationID     *string                        `json:"organization_id,omitempty"`
	PreviousAttributes *WorkOSGroupPreviousAttributes `json:"previous_attributes,omitempty"`
	RawAttributes      *WorkOSGroupRawAttributes      `json:"raw_attributes,omitempty"`
	UpdatedAt          *time.Time                     `json:"updated_at,omitempty"`
}
