// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *DemoResourceModel) ToCreateSDKType() *shared.DemoParams {
	email := new(string)
	if !r.Email.IsUnknown() && !r.Email.IsNull() {
		*email = r.Email.ValueString()
	} else {
		email = nil
	}
	permission := new(shared.DemoParamsPermission)
	if !r.Permission.IsUnknown() && !r.Permission.IsNull() {
		*permission = shared.DemoParamsPermission(r.Permission.ValueString())
	} else {
		permission = nil
	}
	out := shared.DemoParams{
		Email:      email,
		Permission: permission,
	}
	return &out
}

func (r *DemoResourceModel) ToDeleteSDKType() *shared.DemoParams {
	out := r.ToCreateSDKType()
	return out
}

func (r *DemoResourceModel) RefreshFromCreateResponse(resp *shared.Demo) {
	if resp.CreatedAt != nil {
		r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	} else {
		r.CreatedAt = types.StringNull()
	}
	if resp.ID != nil {
		r.ID = types.Int64Value(*resp.ID)
	} else {
		r.ID = types.Int64Null()
	}
	if resp.UpdatedAt != nil {
		r.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
	} else {
		r.UpdatedAt = types.StringNull()
	}
	if resp.UserID != nil {
		r.UserID = types.StringValue(*resp.UserID)
	} else {
		r.UserID = types.StringNull()
	}
}
