// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"abbey/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *IdentityResourceModel) ToCreateSDKType() *shared.IdentityParams {
	linked := make(map[string][]interface{})
	// Warning. This is a map, but the source tf var is not a map. This might indicate a bug.
	name := r.Name.ValueString()
	out := shared.IdentityParams{
		Linked: linked,
		Name:   name,
	}
	return &out
}

func (r *IdentityResourceModel) ToGetSDKType() *shared.IdentityParams {
	out := r.ToCreateSDKType()
	return out
}

func (r *IdentityResourceModel) ToDeleteSDKType() *shared.IdentityParams {
	out := r.ToCreateSDKType()
	return out
}

func (r *IdentityResourceModel) RefreshFromGetResponse(resp *shared.Identity) {
	r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	r.ID = types.StringValue(resp.ID)
	// Not Implemented resp.Linked, {"AssociatedTypes":[],"Enum":null,"RefType":"","Truncated":false,"Output":false,"Name":"","ItemType":{"Input":false,"Examples":[],"Name":"","ItemType":{"Enum":null,"RefType":"","Discriminator":null,"Type":"any","ItemType":null,"Scope":"","Output":false,"Extensions":{"x-untouched":true,"x-speakeasy-param-computed":true,"x-speakeasy-param-force-new":true,"Symbol":""},"Examples":[],"AdditionalProperties":null,"AssociatedTypes":[],"Input":false,"Format":"","Name":"","Fields":[],"BaseName":"","Truncated":false,"Comments":null},"Scope":"","BaseName":"","Truncated":false,"Comments":null,"Output":false,"Extensions":{"x-untouched":true,"x-speakeasy-param-computed":true,"x-speakeasy-param-force-new":true},"AdditionalProperties":null,"Discriminator":null,"Type":"array","Enum":null,"Fields":[],"AssociatedTypes":[],"RefType":"","Format":""},"Scope":"","Comments":null,"Format":"","Type":"map","Fields":[],"AdditionalProperties":null,"BaseName":"","Input":false,"Extensions":{"x-untouched":true,"x-speakeasy-param-computed":true,"x-speakeasy-param-force-new":true},"Examples":[],"Discriminator":null}, false, , , r.Linked
	r.Name = types.StringValue(resp.Name)
}

func (r *IdentityResourceModel) RefreshFromCreateResponse(resp *shared.Identity) {
	r.RefreshFromGetResponse(resp)
}
