// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *IdentityDataSourceModel) RefreshFromGetResponse(resp *shared.Identity) {
	r.AbbeyAccount = types.StringValue(resp.AbbeyAccount)
	r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	r.ID = types.StringValue(resp.ID)
	r.Metadata = types.StringValue(resp.Metadata)
	r.Source = types.StringValue(resp.Source)
	r.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
