// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"terraform/internal/sdk/pkg/models/shared"
	"time"
)

func (r *IdentityResourceModel) ToCreateSDKType() *shared.IdentityParams {
	linked := make(map[string][]interface{})
	// Warning. This is a map, but the source tf var is not a map. This might indicate a bug.
	name := r.Name.ValueString()
	out := shared.IdentityParams{
		Linked: linked,
		Name:   name,
	}
	return &out
}

func (r *IdentityResourceModel) ToGetSDKType() *shared.IdentityParams {
	out := r.ToCreateSDKType()
	return out
}

func (r *IdentityResourceModel) ToDeleteSDKType() *shared.IdentityParams {
	out := r.ToCreateSDKType()
	return out
}

func (r *IdentityResourceModel) RefreshFromGetResponse(resp *shared.Identity) {
	r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	r.ID = types.StringValue(resp.ID)
	// Not Implemented resp.Linked, {"ItemType":{"Format":"","Truncated":false,"Examples":[],"Scope":"","BaseName":"","RefType":"","Comments":null,"Input":false,"Extensions":{"x-untouched":true,"x-speakeasy-param-computed":true},"AssociatedTypes":[],"Enum":null,"AdditionalProperties":null,"Discriminator":null,"Fields":[],"Output":false,"Name":"","ItemType":{"Fields":[],"BaseName":"","Input":false,"Name":"","Type":"any","AssociatedTypes":[],"RefType":"","Comments":null,"AdditionalProperties":null,"ItemType":null,"Scope":"","Truncated":false,"Extensions":{"Symbol":"","x-untouched":true,"x-speakeasy-param-computed":true},"Examples":[],"Enum":null,"Output":false,"Format":"","Discriminator":null},"Type":"array"},"Scope":"","Output":false,"Type":"map","Enum":null,"RefType":"","Input":false,"Examples":[],"Truncated":false,"Comments":null,"Format":"","Discriminator":null,"Name":"","Fields":[],"AssociatedTypes":[],"BaseName":"","Extensions":{"x-untouched":true,"x-speakeasy-param-computed":true},"AdditionalProperties":null}, false, , , r.Linked
	r.Name = types.StringValue(resp.Name)
}

func (r *IdentityResourceModel) RefreshFromCreateResponse(resp *shared.Identity) {
	r.RefreshFromGetResponse(resp)
}
