// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Reviewers struct {
	AllOf []types.String `tfsdk:"all_of"`
	OneOf []types.String `tfsdk:"one_of"`
}
