// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Output struct {
	Append    types.String `tfsdk:"append"`
	Location  types.String `tfsdk:"location"`
	Overwrite types.String `tfsdk:"overwrite"`
}
