// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Review struct {
	CreatedAt         types.String `tfsdk:"created_at"`
	Grant             *Grant       `tfsdk:"grant"`
	GrantID           types.String `tfsdk:"grant_id"`
	GrantKitName      types.String `tfsdk:"grant_kit_name"`
	GrantKitVersionID types.String `tfsdk:"grant_kit_version_id"`
	ID                types.String `tfsdk:"id"`
	Reason            types.String `tfsdk:"reason"`
	RequestID         types.String `tfsdk:"request_id"`
	Status            types.String `tfsdk:"status"`
	UpdatedAt         types.String `tfsdk:"updated_at"`
	UserEmail         types.String `tfsdk:"user_email"`
	UserID            types.String `tfsdk:"user_id"`
}
