// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Grant struct {
	CreatedAt         types.String `tfsdk:"created_at"`
	Deleted           types.Bool   `tfsdk:"deleted"`
	GrantKitID        types.String `tfsdk:"grant_kit_id"`
	GrantKitVersionID types.String `tfsdk:"grant_kit_version_id"`
	ID                types.String `tfsdk:"id"`
	OrganizationID    types.String `tfsdk:"organization_id"`
	RequestID         types.String `tfsdk:"request_id"`
	UpdatedAt         types.String `tfsdk:"updated_at"`
	UserID            types.String `tfsdk:"user_id"`
}
