// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Policy struct {
	Bundle types.String `tfsdk:"bundle"`
	Query  types.String `tfsdk:"query"`
}
