// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Request struct {
	CreatedAt         types.String `tfsdk:"created_at"`
	GrantID           types.String `tfsdk:"grant_id"`
	GrantKitID        types.String `tfsdk:"grant_kit_id"`
	GrantKitName      types.String `tfsdk:"grant_kit_name"`
	GrantKitVersionID types.String `tfsdk:"grant_kit_version_id"`
	ID                types.String `tfsdk:"id"`
	Reason            types.String `tfsdk:"reason"`
	Reviews           []Review     `tfsdk:"reviews"`
	Status            types.String `tfsdk:"status"`
	UpdatedAt         types.String `tfsdk:"updated_at"`
	UserID            types.String `tfsdk:"user_id"`
}
