// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type CancelRequestByIDRequest struct {
	RequestCancelParams shared.RequestCancelParams `request:"mediaType=application/json"`
	// The ID of the request to cancel
	RequestID string `pathParam:"style=simple,explode=false,name=request_id"`
}

type CancelRequestByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	Request *shared.Request
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
