// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateRequestResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Created
	Request     *shared.Request
	StatusCode  int
	RawResponse *http.Response
}
