// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateRequestableResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Created
	Requestable *shared.Requestable
	StatusCode  int
	RawResponse *http.Response
}
