// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateDirectoryResponse struct {
	ContentType string
	// Created
	DirectorySync *shared.DirectorySync
	// Request Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
