// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateSamlConnectionResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Created
	SamlConnection *shared.SamlConnection
	StatusCode     int
	RawResponse    *http.Response
}
