// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteSamlConnectionByIDRequest struct {
	// The ID of the SAML connection to update
	SamlConnectionID string `pathParam:"style=simple,explode=false,name=saml_connection_id"`
}

type DeleteSamlConnectionByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
