// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteIdentityRequest struct {
	// The ID of the identity to delete
	IdentityID string `pathParam:"style=simple,explode=false,name=identity_id"`
}

type DeleteIdentityResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
