// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteAPIKeyRequest struct {
	// The API Key to delete.
	APIKey string `pathParam:"style=simple,explode=false,name=api-key"`
}

type DeleteAPIKeyResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
