// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteRequestableRequest struct {
	// The ID of the requestable to delete
	RequestableID string `pathParam:"style=simple,explode=false,name=requestable_id"`
}

type DeleteRequestableResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
