// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type DeleteGrantKitRequest struct {
	// The ID of the grant kit or resource to delete
	GrantKitIDOrName string `pathParam:"style=simple,explode=false,name=grant_kit_id_or_name"`
}

type DeleteGrantKitResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
