// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type DenyReviewRequest struct {
	ReviewUpdateParams shared.ReviewUpdateParams `request:"mediaType=application/json"`
	// The ID of the review to deny
	ReviewID string `pathParam:"style=simple,explode=false,name=review_id"`
}

type DenyReviewResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	Review      *shared.Review
	StatusCode  int
	RawResponse *http.Response
}
