// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetConnectionRequest struct {
	// The ID of the connection to retrieve
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
}

type GetConnectionResponse struct {
	// Success
	Connection  *shared.Connection
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
