// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetDemoRequest struct {
	// The email of the user
	Email string `queryParam:"style=form,explode=true,name=email"`
}

type GetDemoResponse struct {
	ContentType string
	// Success
	Demo *shared.Demo
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
