// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetGrantByIDRequest struct {
	// The ID of the grant to retrieve
	GrantID string `pathParam:"style=simple,explode=false,name=grant_id"`
}

type GetGrantByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Grant *shared.Grant
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
