// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetGrantByIDRequest struct {
	// The ID of the grant to retrieve
	GrantID string `pathParam:"style=simple,explode=false,name=grant_id"`
}

type GetGrantByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Grant       *shared.Grant
	StatusCode  int
	RawResponse *http.Response
}
