// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetGrantKitsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	GrantKits   []shared.GrantKit
	StatusCode  int
	RawResponse *http.Response
}
