// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetIdentityRequest struct {
	// The ID of the identity to retrieve
	IdentityID string `pathParam:"style=simple,explode=false,name=identity_id"`
}

type GetIdentityResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Identity    *shared.Identity
	StatusCode  int
	RawResponse *http.Response
}
