// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetReviewByIDRequest struct {
	// The ID of the review to retrieve.
	ReviewID string `pathParam:"style=simple,explode=false,name=review_id"`
}

type GetReviewByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Review      *shared.Review
	StatusCode  int
	RawResponse *http.Response
}
