// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetRequestableByIDRequest struct {
	// The ID of the requestable to retrieve.
	RequestableID string `pathParam:"style=simple,explode=false,name=requestable_id"`
}

type GetRequestableByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Requestable *shared.Requestable
	StatusCode  int
	RawResponse *http.Response
}
