// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetRequestByIDRequest struct {
	// The ID of the request to retrieve
	RequestID string `pathParam:"style=simple,explode=false,name=request_id"`
}

type GetRequestByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Request     *shared.Request
	StatusCode  int
	RawResponse *http.Response
}
