// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetTaskByIDRequest struct {
	// The ID of the task to retrieve
	TaskID string `pathParam:"style=simple,explode=false,name=task_id"`
}

type GetTaskByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// Success
	Task *shared.Task
}
