// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListSamlConnectionsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	SamlConnections *shared.SamlConnections
	StatusCode      int
	RawResponse     *http.Response
}
