// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListRequestsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Requests    []shared.Request
	StatusCode  int
	RawResponse *http.Response
}
