// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListOauthsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	OauthListing *shared.OauthListing
	StatusCode   int
	RawResponse  *http.Response
}
