// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListRequestablesResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Requestables []shared.Requestable
	StatusCode   int
	RawResponse  *http.Response
}
