// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListTasksResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// Success
	Tasks []shared.Task
}
