// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type RevokeGrantRequest struct {
	// The ID of the grant to revoke
	GrantID string `pathParam:"style=simple,explode=false,name=grant_id"`
}

type RevokeGrantResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	Grant       *shared.Grant
	StatusCode  int
	RawResponse *http.Response
}
