// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type UpdateTaskRequest struct {
	Task   shared.Task `request:"mediaType=application/json"`
	TaskID string      `pathParam:"style=simple,explode=false,name=task_id"`
}

type UpdateTaskResponse struct {
	ContentType string
	// Request Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// Success
	Task *shared.Task
}
