// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateGrantKitRequest struct {
	GrantKitUpdateParams shared.GrantKitUpdateParams `request:"mediaType=application/json"`
	// The ID of the grant kit or resource to update
	GrantKitIDOrName string `pathParam:"style=simple,explode=false,name=grant_kit_id_or_name"`
}

type UpdateGrantKitResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	GrantKit    *shared.GrantKit
	StatusCode  int
	RawResponse *http.Response
}
