// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateGHEAppRequest struct {
	GithubEnterpriseAppParams shared.GithubEnterpriseAppParams `request:"mediaType=application/json"`
	// The ID of the connection to update
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
}

type UpdateGHEAppResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	GithubEnterpriseApp *shared.GithubEnterpriseApp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
