// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"abbey/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateGrantKitRequest struct {
	GrantKitUpdateParams shared.GrantKitUpdateParams `request:"mediaType=application/json"`
	// The ID of the grant kit or resource to update
	GrantKitIDOrName string `pathParam:"style=simple,explode=false,name=grant_kit_id_or_name"`
}

type UpdateGrantKitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	GrantKit *shared.GrantKit
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
