name: Generate

on:
  workflow_dispatch: # Allows manual triggering of the workflow to generate SDK
    inputs:
      force:
        description: "Force generation of SDKs on main branch"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * * # Runs every day at midnight
  push:
    branches:
      - '*'
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      speakeasy_version: latest
      openapi_doc_auth_header: Authorization
      openapi_docs: |
        - https://raw.githubusercontent.com/Alramech/speakeasy-test/main/openapi/openapi.yaml
      languages: |
        - terraform
      create_release: true
      force: ${{ github.event.inputs.force }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      openapi_doc_auth_token: ${{ secrets.SPEC_TOKEN }}
