name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          # Version pinned until https://github.com/testcontainers/testcontainers-go/issues/1359
          # is resolved.
          go-version: '1.20.5'
          cache: true
          cache-dependency-path: go.sum

      - name: Install golangci-lint
        # Install golangci-lint from source instead of using
        # golangci-lint-action to ensure the golangci-lint binary is built with
        # the same Go version we're targeting.
        # Avoids incompatibility issues such as:
        # - https://github.com/golangci/golangci-lint/issues/2922
        # - https://github.com/golangci/golangci-lint/issues/2673
        # - https://github.com/golangci/golangci-lint-action/issues/442
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.1

      - name: Lint
        run: golangci-lint run --version --verbose --out-format=github-actions --timeout 3m0s
